apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: h2c-server
  name: h2c-server
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: h2c-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: h2c-server
    spec:
      containers:
      - command:
        - tail
        - -f
        - /dev/null
        image: golang:1.15
        imagePullPolicy: IfNotPresent
        name: golang
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30