apiVersion: v1
kind: Service
metadata:
  labels:
    app: h2c-server
  name: h2c-server
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: h2c-server
  sessionAffinity: None
  type: ClusterIP